# Generated by Django 3.2 on 2022-01-05 19:15

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='State',
            fields=[
                ('state_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('state_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='District',
            fields=[
                ('district_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('district_name', models.CharField(max_length=100)),
                ('state', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dhw.state')),
            ],
        ),
        migrations.CreateModel(
            name='Child',
            fields=[
                ('child_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('sex', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=1)),
                ('dob', models.DateField()),
                ('father_name', models.CharField(max_length=100)),
                ('mother_name', models.CharField(max_length=100)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='media/')),
                ('district', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dhw.district')),
                ('state', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dhw.state')),
            ],
        ),
    ]
